spring:
  application:
    name: LEADERBOARD-APPLICATION
  datasource:
    url: jdbc:postgresql://localhost:5432/leaderboard
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 36000
logging:
  level:
    org:
      springframework:
        security:
          DEBUG